### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by dejanp777** [sinanw/llm-security-prompt-injection#1]
Hello,
Thank you for your great work.
I have one issue when trying fine tuning on google colab, I am getting warning that it needs 120GB VRAM, while strongest GPU on google colab in selection has only 40GB VRAM, can you please tell me how you manage to run it?

**Comment by sinanw** [comment]
Hello,

Thank you for reaching out and for your interest. I'm glad to hear that you find my work valuable.

Regarding the VRAM requirement, I don't have a clear idea about the reasons behind this warning. In reality, I've done the fine-tuning with Jupyter Notebook on my local setup with Nvidia RTX A4500 and 20 GB of GPU memory, so I believe the fine-tuning process should be feasible with the available resources on Google Colab.

I would suggest double-checking your fine-tuning configuration and make sure that you're using the correct settings and parameters. Sometimes, default configurations might specify higher VRAM requirements than necessary. Additionally, try lower batch size values during fine-tuning since smaller batch sizes might reduce the VRAM requirement.
